# Generated by Django 5.0 on 2024-01-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Date'),
        ),
    ]
